[config]
default_to_workspace = false
skip_core_tasks = true

[env]
PROJ_NAME = "serde-encrypt-sgx"

[tasks.format]
script = ['''
#!/usr/bin/env bash -eux
cargo fmt --all
''']

[tasks.lint]
script = ['''
#!/usr/bin/env bash -eux
RUSTFLAGS='-D warnings' cargo clippy --workspace --all-targets --all-features
''']

[tasks.build-sgx]
script = [
  '''
#!/usr/bin/env bash -eux
docker run --rm -v `pwd`:/root/serde-encrypt-sgx baiduxlab/sgx-rust:1804-1.1.3 bash -c '
    export PATH=/root/.cargo/bin:$PATH
    cd /root/serde-encrypt-sgx
    rustup show
    RUSTFLAGS="-D warnings" cargo build --all-features
'
''',
]
